### ISSUE TITLE
Implement Automated Testing for Terraform Modules

### ISSUE THREAD

**Issue by osterman** [cloudposse/testing.cloudposse.co#4]
## what
1. provision a `codefresh-terraform` user with https://github.com/cloudposse/terraform-aws-iam-system-user

## why
* Codefresh is external to AWS, so we cannot use instance profiles
* We need the credentials so that codefresh can run the CI/CD

**Comment by aknysh** [comment]
we'll create a module `terraform-aws-iam-codefresh-user` to provision a user with the required permissions, will output the key Id and secret key.
similar to https://github.com/cloudposse/terraform-aws-iam-chamber-user

**Comment by Nuru** [comment]
Done, and superseded. Testing moved to GitHub actions with `test-harness`
